---
- name: Atualizando pacotes 'apt update/ apt augrade'
  apt:
    update_cache: yes
    upgrade: full

- name: Instalando 'Python 3'
  apt:
    name: "{{ packages}}"
  vars:
    packages:
    - python3
    - python3-pip
    - python3-dev
...
